### ISSUE TITLE
Feature: Having a default Category

### ISSUE THREAD

**Issue by Danie10** [Dacid99/LinkDroid-for-Linkwarden#1]
App is working really well, and I like that the name, etc can be left blank for quick saving. Just wondering if there is/will be a way to speed it up even more and have the ability to set a default category e.g. Unorganised to be can queue up stuff for later actions?

I have a long list of categories so Unorganised is like 3 or so screens of scrolling down to find.

**Comment by Dacid99** [comment]
Hi, I am very sorry for the late reply, for some reason I was not notified of the issues that have been opened in this repository. 
Thank you for the feedback!

Yes I should be able to allow you to set a custom default category in the app preferences.
Ill effort to make this part of the next release (approximately coming next weekend).

**Comment by Danie10** [comment]
No problem, thanks for responding. It's not critical as the app is actually working really well. It's really a nice to have that will add an extra touch. OK great, I'll watch out for the next release.

**Comment by Dacid99** [comment]
I just released the new version :partying_face: , you can now pick a default collection in the settings slider. 
Please let me know whether this works for you. 
Ill close the issue as resolved until further notice.
