### ISSUE TITLE
Feature request: add support for Readeck

### ISSUE THREAD

**Issue by aia832003** [Dacid99/LinkDroid-for-Linkwarden#13]
First, I use both services but prefer Readeck. I'd love to see support for both. They seem to be the best self-hosted options for read it later that don't currently have first party apps on Android.

https://readeck.org/en/docs/

**Comment by Dacid99** [comment]
Hey, thanks for the idea but I think it would be more reasonable to have a separate app for this.
This could be a fork of this project with all linkwarden api stuff replaced by readecks api.
Currently I lack the time to do this but feel free to go ahead and do it yourself, it should be fairly straightforward.

**Comment by aia832003** [comment]
Thanks for the quick response. I wish I had the skills to pull that off, but hey, maybe I give it shot. lol
