### ISSUE TITLE
UI behind the notification bar, cant press buttons

### ISSUE THREAD

**Issue by dariusaurius** [Dacid99/LinkDroid-for-Linkwarden#14]
Hi,

thanks for your app! 

My Pixel 8 has a issue with the scaling of the app. The notification bar is in front of the app which makes it impossible to press the buttons and use the search on the top:

![telegram-cloud-photo-size-2-5334807530544685254-y](https://github.com/user-attachments/assets/0af5a21e-54e5-466e-abc7-dce6a4e1ccc2)

Hope you have a way to reproduce this and that it is not to hard to fix. 

Reagrds

**Comment by d0dg3r** [comment]
Hello, thanks for the info. It will be fixed in a newer version.

Greetings

**Comment by dariusaurius** [comment]
Thats very kind of you! Thanks

**Comment by Dacid99** [comment]
Hey please try the latest version 2.0.0 and let me know whether this solves the problem.

**Comment by dariusaurius** [comment]
Finaly Linkwarden-Godness on my Android, I appreciate your afford very much. Thank you
