### ISSUE TITLE
Unable to submit input

### ISSUE THREAD

**Issue by hllshiro** [Dacid99/LinkDroid-for-Linkwarden#15]
As shown in the video, I can't submit my configuration information to the input box after entering it, what should I do?

https://github.com/user-attachments/assets/6b74dc7e-56c1-4737-a11d-d3e68f6a7c98

**Comment by hllshiro** [comment]
The device I'm using is Android 13.

I modified the source code but it didn't work, sorry but I'm not familiar with Android development.

```xml
<EditTextPreference
        app:key="BASE_URL"
        app:title="@string/base_url_title"
        app:summary="@string/base_url_summary"
        app:useSimpleSummaryProvider="true"
        app:iconSpaceReserved="false"
        android:negativeButtonText="CANCEL"
        android:positiveButtonText="OK" />

    <EditTextPreference
        app:key="AUTH_TOKEN"
        app:title="@string/auth_token_title"
        app:summary="@string/auth_token_summary"
        app:useSimpleSummaryProvider="true"
        app:iconSpaceReserved="false"
        android:negativeButtonText="CANCEL"
        android:positiveButtonText="OK" />
```

**Comment by Dacid99** [comment]
Hey,
this is a weird issue. There should be a button in the righthand-side corner that lets you enter the data. 
Maybe this is a font color problem so white text on white background? Have you tried clicking in the right corner where the button should be positioned?

Thanks for the code idea, Ill effort to add this feature to the upcoming version!

**Comment by hllshiro** [comment]
Thanks, I tested it and it is true that the button is hidden. 🤣

**Comment by hllshiro** [comment]
I submitted a new PR in gitlab, but it was only tested on my device, please check it

**Comment by Dacid99** [comment]
Ill look into it, thanks!
