### ISSUE TITLE
How to save any settings?

### ISSUE THREAD

**Issue by swisonline** [Dacid99/LinkDroid-for-Linkwarden#18]
Pixel 7 Pro / Latest Android 

Cannot save any settings. Enter is just a simple 'return'

**Comment by hllshiro** [comment]
On some models, the button will be hidden in light mode, and it can be visible when you switch to dark mode or you can save it by clicking its position directly.
![edit](https://github.com/user-attachments/assets/3cf1067e-0ef8-417d-a230-af3a8b29ba35)

**Comment by swisonline** [comment]
😂 thank you. It's working

**Comment by Dacid99** [comment]
Fixed in version 2.0.0
