### ISSUE TITLE
LinkDroid new tag - characters don't display

### ISSUE THREAD

**Issue by csweningsen** [Dacid99/LinkDroid-for-Linkwarden#21]
Entering new Tag, only blank spaces display; but on Enter they show up and Tag is in fact created.

**Comment by Dacid99** [comment]
Hi thanks for the info.
Does this happen in light or dark mode or both?

**Comment by csweningsen** [comment]
Ah, seems light mode only.

----- Original Message -----

**Comment by Dacid99** [comment]
Ok then it should be easy to fix, I have added it to my todos 
Thanks for reporting this!

**Comment by csweningsen** [comment]
And thanks to you for all,

Christian
----- Original Message -----

**Comment by Dacid99** [comment]
I just fixed this in the [latest commit](https://github.com/Dacid99/LinkDroid-for-Linkwarden/commit/fab51ef3282bc00ee9a16cb6c5cfd2d7c5aca67b).
The release with the fix should be on f-droid in a couple of days. 
If it's urgent you can go fetch it from the [gitlab repo](https://gitlab.com/Dacid99/linkdroid-for-linkwarden/-/releases/v2.0.1)
Thanks again for making me aware of this.

**Comment by csweningsen** [comment]
Thanks again

Christian

----- Original Message -----
