### ISSUE TITLE
Allow to set multiple Tags

### ISSUE THREAD

**Issue by jvanbruegge** [Dacid99/LinkDroid-for-Linkwarden#3]
Thanks for the app, it works quite well. As far as I can tell I can only add a single tag to a link, would it be possible to allow multiple tags, e.g. via comma separation?

**Comment by Dacid99** [comment]
Hi, I am very sorry for the late reply, for some reason I was not notified of the issues that have been opened in this repository. 

You should be able to enter multiple tags by clicking the enter of your keyboard at the end of each tag, just like you do in the browser extension. That click should then add a chip above the field. 
Ill try to explain this behaviour better in the field hint.

**Comment by WinstonSmith73** [comment]
I can confirm that hitting enter let's me add multiple tags. Didn't realize until I saw your comment above :)

**Comment by Dacid99** [comment]
Ok thx for confirming this.
I guess Ill have to improve the hint on that field once more 😅

**Comment by jvanbruegge** [comment]
I have not yet tried adding multiple tags, but even if I add a single tag, the article does not actually have the tag in linkwarden afterwards

**Comment by Dacid99** [comment]
Does the tag you want to add appear as a [chip](https://m3.material.io/components/chips/overview) above the entry field for the tags?
Only these tags are used in the api request

**Comment by Dacid99** [comment]
Youre right, and there will be some changes to this with the next release anyway. 
Ill try to include this improved behaviour.
Thanks for making me aware of this!

**Comment by Dacid99** [comment]
Fixed in version 2.0.0
