### ISSUE TITLE
Set default Name 

### ISSUE THREAD

**Issue by itguy327** [Dacid99/LinkDroid-for-Linkwarden#4]
Thank you for your work 

Would it be possible to set the name automatically similar to the chrome extension for linkwarden

**Comment by Dacid99** [comment]
Hi, I am very sorry for the late reply, for some reason I was not notified of the issues that have been opened in this repository. 

Thank you for the feedback and this idea!  

I would say that should be possible in theory but it would require a lot of effort. 
See, if you use the app to save a link, the android system send an intent to the Linkdroid app. That intent only includes the link url string even if sent from the browser. 
So to realize this feature, the webpage would have to be loaded in the background to extract a link name. For the webextension its much easier to get this data as it has full access to the webpage.
Ill put this into my TODOs and if Im looking for a challenge at some later point I will try to implement it.

**Comment by itguy327** [comment]
Thank you. I appreciate your work and keeping the idea in mind. I
definitely get the complexity

**Comment by Dacid99** [comment]
I just added the feature to my todo list. Ill close this issue for the time being.
Please let me know if you have other ideas or issues with the app.

**Comment by itguy327** [comment]
Thank you

**Comment by Dacid99** [comment]
Implemented in version 2.0.0
