### ISSUE TITLE
feature: add error checking on share dialog

### ISSUE THREAD

**Issue by program-the-brain-not-the-heartbeat** [Dacid99/LinkDroid-for-Linkwarden#5]
Please add some basic error checking on the share dialog so I cannot accidentally try to save a link without the name field not empty.

Thanks!

**Comment by Dacid99** [comment]
Hi thanks for the feedback!

I guess not all users will want to be forced to add a name. Ill add a setting to enable this behaviour. 
Should come with the next update on the weekend. 👍

**Comment by Dacid99** [comment]
I just added the feature in the new release, please test it and let me know if there is something wrong.
Thanks again for the input!
Ill close this issue until further notice.
